issueTrackerURL = "https://github.com/ms0503/mc-server-auto-closer/issues"
license = "MIT"
loaderVersion = "[4.9,)"
modLoader = "kotlinforforge"

[[dependencies."${mod_id}"]]
mandatory = true
modId = "architectury"
ordering = "AFTER"
side = "BOTH"
versionRange = "[11.0.7,)"

[[dependencies."${mod_id}"]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "SERVER"
versionRange = "[49.0.3,)"

[[dependencies."${mod_id}"]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "SERVER"
versionRange = "[1.20.4]"

[[mods]]
authors = "Sora Tonami"
description = """${description}"""
displayName = "${mod_name}"
modId = "${mod_id}"
version = "${version}"
