issueTrackerURL = "https://github.com/ms0503/mc-server-auto-closer/issues"
license = "MIT"
loaderVersion = "[4.3,)"
modLoader = "kotlinforforge"

[[dependencies."${mod_id}"]]
mandatory = true
modId = "architectury"
ordering = "AFTER"
side = "BOTH"
versionRange = "[9.0.6,)"

[[dependencies."${mod_id}"]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "SERVER"
versionRange = "[46.0.1,)"

[[dependencies."${mod_id}"]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "SERVER"
versionRange = "[1.20,1.20.1]"

[[mods]]
authors = "Sora Tonami"
description = """${description}"""
displayName = "${mod_name}"
modId = "${mod_id}"
version = "${version}"
